[tool.poetry]
name = "cloelib"
version = "0.1.0"
description = "cloelib is a flexible and efficient library designed to compute cosmological observables for the CLOE (Cosmology Likelihood for Observables in Euclid) project"
authors = ["cloe-maintainers <cloe-maintainers@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
jax = "^0.4"
jaxlib = "^0.4"
interpax = "^0.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
