name: Docs

on:
  push:
    branches:
      - main        # Pushes to main update 'dev'
    tags:
      - 'v*'        # Tags update 'stable' and version numbers
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev gfortran

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings[python] mike
          pip install -e .

      - name: Fetch gh-pages history
        run: git fetch origin gh-pages --depth=1 || true

      - name: Configure git author
        run: |
          git config --local user.name  "${{ github.actor }}"
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Deploy documentation
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "Deploying release $VERSION"

            # Push the specific version AND update the 'stable' alias
            mike deploy --push --update-aliases $VERSION stable
            mike set-default --push stable

          # If the Main branch is pushed
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "Deploying dev docs from main"

            # Update 'dev' and alias it to 'latest'
            mike deploy --push --update-aliases dev latest
          fi
